# Generated by Django 5.1.1 on 2024-10-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failuire')], default='sucess', max_length=10),
        ),
        migrations.AlterField(
            model_name='history',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('debit', 'Debit')], default='deposit', max_length=10),
        ),
    ]
